modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="thornsinyou" #mandatory
version="1.20.1-1.0.0" #mandatory
displayName="\u00A74Thorns In You\u00A7r" #mandatory
authors="Destiny" #optional

description='''Here will be a description. Cool tea mod'''

[[dependencies.thornsinyou]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.thornsinyou]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.thornsinyou]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.4,)"
    ordering="NONE"
    side="BOTH"